{
 "title": "Kopano dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LDAP auth fail",
   "type": "stat",
   "description": "LDAP authentication failure",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kopano_server_ldap_auth_fail" }
   ]
  },
  {
   "title": "Sessions Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kopano_server_sessions", "legendFormat": "sessions" }
   ]
  },
  {
   "title": "Sessions Created / Deleted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kopano_server_sessions_created[5m])",
     "legendFormat": "created"
    },
    {
     "expr": "rate(kopano_server_sessions_deleted[5m])",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "Server queuelen",
   "type": "stat",
   "description": "Current queue length",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "targets": [
    { "expr": "kopano_server_queuelen" }
   ]
  },
  {
   "title": "Mwrops / Mrops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(kopano_server_mrops[5m])", "legendFormat": "mrops" },
    { "expr": "rate(kopano_server_mwops[5m])", "legendFormat": "mrops" }
   ]
  },
  {
   "title": "Kopano SQL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kopano_server_sql_select[5m])",
     "legendFormat": "select"
    },
    {
     "expr": "rate(kopano_server_sql_delete[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(kopano_server_sql_update[5m])",
     "legendFormat": "update"
    },
    {
     "expr": "rate(kopano_server_sql_connect[5m])",
     "legendFormat": "connect"
    }
   ]
  },
  {
   "title": "Round Trip Time",
   "type": "graph",
   "description": "The rate of response time  / soap request time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(kopano_server_response_time[5m])/rate(kopano_server_soap_request[5m])",
     "legendFormat": "rtt"
    }
   ]
  },
  {
   "title": "Memory statistics",
   "type": "graph",
   "description": "Kopano server tcmalloc statistics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kopano_server_tc_allocated[5m])",
     "legendFormat": "tcmalloc allocated"
    }
   ]
  },
  {
   "title": "Object cache",
   "type": "gauge",
   "description": "The object cache hit ratio",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kopano_server_cache_obj_hit * 100 / kopano_server_cache_obj_req"
    }
   ]
  },
  {
   "title": "Cell cache",
   "type": "gauge",
   "description": "The cell cache hit ratio",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "targets": [
    {
     "expr": "kopano_server_cache_cell_hit * 100 / kopano_server_cache_cell_req"
    }
   ]
  },
  {
   "title": "abinfo cache",
   "type": "gauge",
   "description": "The abinfo cache hit ratio",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "kopano_server_cache_abinfo_hit * 100 / kopano_server_cache_abinfo_req"
    }
   ]
  },
  {
   "title": "Index1 cache",
   "type": "gauge",
   "description": "The index1 cache hit ratio",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "kopano_server_cache_index1_hit * 100 / kopano_server_cache_index1_req"
    }
   ]
  },
  {
   "title": "Index2 cache",
   "type": "gauge",
   "description": "The store cache hit ratio",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "kopano_server_cache_index2_hit * 100 / kopano_server_cache_index2_req"
    }
   ]
  },
  {
   "title": "Extern cache",
   "type": "gauge",
   "description": "The extern cache hit ratio",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
   "targets": [
    {
     "expr": "kopano_server_cache_extern_hit * 100 / kopano_server_cache_extern_req"
    }
   ]
  },
  {
   "title": "Object cache",
   "type": "gauge",
   "description": "The object cache size ratio",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kopano_server_cache_obj_size * 100 / kopano_server_cache_obj_maxsz"
    }
   ]
  },
  {
   "title": "Cell cache",
   "type": "gauge",
   "description": "The object cell size ratio",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "kopano_server_cache_cell_size * 100 / kopano_server_cache_cell_maxsz"
    }
   ]
  },
  {
   "title": "abinfo cache",
   "type": "gauge",
   "description": "The abinfo cache size ratio",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "kopano_server_cache_abinfo_size * 100 / kopano_server_cache_abinfo_maxsz"
    }
   ]
  },
  {
   "title": "index1 cache",
   "type": "gauge",
   "description": "The index1 cache size ratio",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "kopano_server_cache_index1_size * 100 / kopano_server_cache_index1_maxsz"
    }
   ]
  },
  {
   "title": "index2 cache",
   "type": "gauge",
   "description": "The index2 cache size ratio",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "kopano_server_cache_index2_size * 100 / kopano_server_cache_index2_maxsz"
    }
   ]
  },
  {
   "title": "Extern cache",
   "type": "gauge",
   "description": "The extern cache size ratio",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 28 },
   "targets": [
    {
     "expr": "kopano_server_cache_extern_size * 100 / kopano_server_cache_extern_maxsz"
    }
   ]
  }
 ]
}